Repository DUNE-DAQ/trgtools, pull requests merged in 2024-02, with the labels that each got.

#8 TA & TP Summary Statistics
  .gitignore
  apps/ta_dump.py
  apps/tp_dump.py
  docs/ta-dump.md
  docs/tp-dump.md
Labels: miscellaneous deliverable

#9 Added more TP histograms.
  apps/tp_dump.py
Labels: miscellaneous deliverable

#11 Removed Fragment Separation From TAData & TPData Classes
  apps/ta_dump.py
  apps/tp_dump.py
  python/trgtools/TAData.py
  python/trgtools/TPData.py
Labels: miscellaneous deliverable

#15 Remove C Python Binding Import
  python/trgtools/__init__.py
Labels: bug, maintenance, miscellaneous deliverable

#16 Cherry-picked Alex's fix for Issue 14 from the production/v4 branch for the prep-release branch
  python/trgtools/__init__.py
Labels: miscellaneous deliverable

#17 Using HDF5 File Attributes To Separate Outputs
  apps/ta_dump.py
  apps/tp_dump.py
  python/trgtools/TAData.py
  python/trgtools/TPData.py
Labels: miscellaneous deliverable

#19 TC Data Class & Plots
  apps/tc_dump.py
  docs/README.md
  docs/tc-dump.md
  python/trgtools/TCData.py
  python/trgtools/__init__.py
Labels: enhancement, miscellaneous deliverable

#21 Added TC Processing
  apps/process_tpstream.cxx
Labels: enhancement, miscellaneous deliverable

#22 Updated TA & TP Plotting Style
  apps/ta_dump.py
  docs/ta-dump.md
  docs/tp-dump.md
  python/trgtools/TAData.py
  scripts/ta_dump.py
  scripts/tc_dump.py
  scripts/tp_dump.py
Labels: maintenance, miscellaneous deliverable

#23 Python Style Update
  docs/README.md
  docs/py-trgtools.md
  docs/ta-dump.md
  docs/tc-dump.md
  docs/tp-dump.md
  python/setup.cfg
  python/trgtools/HDF5Reader.py
  python/trgtools/TAData.py
  python/trgtools/TAReader.py
  python/trgtools/TCData.py
  python/trgtools/TCReader.py
  python/trgtools/TPData.py
  python/trgtools/TPReader.py
  python/trgtools/__init__.py
  python/trgtools/plot/PDFPlotter.py
  python/trgtools/plot/__init__.py
  requirements.txt
  scripts/ta_dump.py
  scripts/tc_dump.py
  scripts/tp_dump.py
Labels: documentation, enhancement, miscellaneous deliverable
